# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_standardpage_standardpagerelatedlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardpage',
            old_name='stream_field',
            new_name='page_content',
        ),
        migrations.RenameField(
            model_name='standardpage',
            old_name='body',
            new_name='plain_content',
        ),
    ]
