# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('power', models.IntegerField()),
                ('width', models.IntegerField()),
                ('stow_height', models.IntegerField()),
                ('platform_height', models.IntegerField()),
                ('platform_width', models.IntegerField()),
                ('platform_length', models.IntegerField()),
                ('working_height', models.IntegerField()),
                ('drive_speed', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('cost', models.CharField(max_length=255)),
                ('cost_type', models.CharField(choices=[('sale', 'For Sale'), ('lease', 'For Hire')], default='sale', max_length=10)),
            ],
        ),
    ]
