# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftunit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='KG Unit of measurement', null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='cost',
            field=models.CharField(help_text='GBP', max_length=255),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='drive_speed',
            field=models.CharField(blank=True, help_text='MPH', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='platform_height',
            field=models.IntegerField(blank=True, help_text='CM Unit of measurement', null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='platform_length',
            field=models.IntegerField(blank=True, help_text='CM Unit of measurement', null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='platform_width',
            field=models.IntegerField(blank=True, help_text='Unit of measurement', null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='power',
            field=models.IntegerField(blank=True, help_text='Horsepower Unit of measurement', null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='stow_height',
            field=models.IntegerField(blank=True, help_text='CM Unit of measurement', null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='weight',
            field=models.IntegerField(blank=True, help_text='KG Unit of measurement', null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='width',
            field=models.IntegerField(blank=True, help_text='CM Unit of measurement', null=True),
        ),
        migrations.AlterField(
            model_name='liftunit',
            name='working_height',
            field=models.IntegerField(blank=True, help_text='CM Unit of measurement', null=True),
        ),
    ]
